## Add vector datasets

### Add CSV

Read a CSV as a Pandas DataFrame.

In [1]:
import os
import leafmap

In [2]:
in_csv = 'https://raw.githubusercontent.com/opengeos/data/main/world/world_cities.csv'
df = leafmap.csv_to_df(in_csv)
df

        id            name country  latitude  longitude  population
0        1           Bombo     UGA   0.58330   32.53330       75000
1        2     Fort Portal     UGA   0.67100   30.27500       42670
2        3         Potenza     ITA  40.64200   15.79900       69060
3        4      Campobasso     ITA  41.56300   14.65600       50762
4        5           Aosta     ITA  45.73700    7.31500       34062
...    ...             ...     ...       ...        ...         ...
1244  1245  Rio de Janeiro     BRA -22.92502  -43.22502    11748000
1245  1246       Sao Paulo     BRA -23.55868  -46.62502    18845000
1246  1247          Sydney     AUS -33.92001  151.18518     4630000
1247  1248       Singapore     SGP   1.29303  103.85582     5183700
1248  1249       Hong Kong     CHN  22.30498  114.18501     7206000

[1249 rows x 6 columns]

Create a point layer from a CSV file containing lat/long information.

In [11]:
m = leafmap.Map(attribution_control=False)
m.add_xy_data(in_csv, x="longitude", y="latitude", layer_name="World Cities")
m

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

Set the output directory.

In [4]:
out_dir = os.getcwd()
out_shp = os.path.join(out_dir, 'world_cities.shp')

Convert a CSV file containing lat/long information to a shapefile.

In [5]:
leafmap.csv_to_shp(in_csv, out_shp)

Convert a CSV file containing lat/long information to a GeoJSON.

In [6]:
out_geojson = os.path.join(out_dir, 'world_cities.geojson')
leafmap.csv_to_geojson(in_csv, out_geojson)

Convert a CSV file containing lat/long information to a GeoPandas GeoDataFrame.

In [7]:
gdf = leafmap.csv_to_gdf(in_csv)
gdf

,id,name,country,latitude,longitude,population,geometry
0,1,Bombo,UGA,0.58330,32.53330,75000,POINT (32.5333 0.5833)
1,2,Fort Portal,UGA,0.67100,30.27500,42670,POINT (30.275 0.671)
2,3,Potenza,ITA,40.64200,15.79900,69060,POINT (15.799 40.642)
3,4,Campobasso,ITA,41.56300,14.65600,50762,POINT (14.656 41.563)
4,5,Aosta,ITA,45.73700,7.31500,34062,POINT (7.315 45.737)
...,...,...,...,...,...,...,...
1244,1245,Rio de Janeiro,BRA,-22.92502,-43.22502,11748000,POINT (-43.22502 -22.92502)
1245,1246,Sao Paulo,BRA,-23.55868,-46.62502,18845000,POINT (-46.62502 -23.55868)
1246,1247,Sydney,AUS,-33.92001,151.18518,4630000,POINT (151.18518 -33.92001)
1247,1248,Singapore,SGP,1.29303,103.85582,5183700,POINT (103.85582 1.29303)
1248,1249,Hong Kong,CHN,22.30498,114.18501,7206000,POINT (114.18501 22.30498)